apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlinkstatus
  namespace: monitoring
spec:
  replicas: 0
  selector:
    matchLabels:
      app: starlinkstatus
  template:
    metadata:
      labels:
        app: starlinkstatus
    spec:
      containers:
      - name: starlinkstatus
        image: thegippygeek/starlinkstatus:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: starlinkstatus
              key: apikey
        envFrom:
        - configMapRef:
            name: starlinkstatus
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
