version: '3.7'
services:
  starlinkstatus:
    build:
      context: .
    restart: always
    environment:
      - APIKEY=YOURAPIKEY
      - SCHEDULE=900
      - DISHY=true
      - SPEEDTEST=true
      - debug=false
      - CRONJOB=false
