apiVersion: batch/v1
kind: CronJob
metadata:
  name: starlink-15min
spec:
  schedule: "15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: starlinkstatus
        spec:
          containers:
          - name: starlinkstatus-15
            image: thegippygeek/starlinkstatus:0.0.12
            env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: starlinkstatus
                  key: apikey
            envFrom:
            - configMapRef:
                name: starlinkstatus-15m
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: starlink-hourly
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: starlinkstatus
        spec:
          containers:
          - name: starlinkstatus-hourly
            image: thegippygeek/starlinkstatus:0.0.12
            env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: starlinkstatus
                  key: apikey
            envFrom:
            - configMapRef:
                name: starlinkstatus-hourly
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
          restartPolicy: OnFailure